# dar-backup-base image
#
#  How to build:
#  sudo docker build -f Dockerfile-base-image -t dar-backup-base:24.04 .
#

FROM ubuntu:24.04

LABEL org.opencontainers.image.source="https://github.com/YOURUSER/dar-backup-image" \
      org.opencontainers.image.description="Container for DAR-based backups using dar-backup" \
      org.opencontainers.image.version="0.5.0-alpha"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  --no-install-recommends \
        python3 \
        python3-pip \
        dar \
        par2 \
        gosu \
        tzdata \
        && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp*
