# dar-backup  
#  
#  How to build:
#  sudo docker build -f Dockerfile-dar-backup -t dar-backup:0.5.0- .
#

FROM dar-backup-base:24.04

LABEL org.opencontainers.image.source="https://github.com/per2jensen/dar-backup-image" \
      org.opencontainers.image.description="Container for DAR-based backups using dar-backup" \
      org.opencontainers.image.version="0.5.0-alpha"

ENV DEBIAN_FRONTEND=noninteractive

# Install your PyPI package globally
RUN pip3 install dar-backup  --break-system-packages

# # Copy config and default backup definitions (optional)
COPY dar-backup.conf /etc/dar-backup/dar-backup.conf

# # Default data paths (can be overridden at runtime)
ENV DAR_BACKUP_CONFIG=/etc/dar-backup/dar-backup.conf
ENV DAR_BACKUP_DIR=/backups
ENV BACKUP_D_DIR=/backup.d

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# # Entrypoint
ENTRYPOINT ["/entrypoint.sh"]
CMD ["--full-backup", "--verbose", "--log-stdout", "--config", "/etc/dar-backup/dar-backup.conf"]
