# SPDX-License-Identifier: GPL-3.0-or-later
#
# dar-backup-base image
#
#  How to build:
#  sudo docker build -f Dockerfile-base-image -t dar-backup-base:24.04 .
#

FROM ubuntu:24.04

ARG VERSION=0.0.0
LABEL org.opencontainers.image.source="https://github.com/per2jensen/dar-backup-image" \
      org.opencontainers.image.description="Container for DAR-based backups using `dar-backup`" \
      org.opencontainers.image.version="${VERSION}"


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        util-linux \
        python3 \
        python3-pip \
        dar \
        par2 \
        tzdata && \
    # Remove man pages, docs, locales, and unused share files
    rm -rf /usr/share/man/* \
           /usr/share/doc/* \
           /usr/share/doc-base/* \
           /usr/share/locale/* \
           /usr/share/info/* \
           /var/lib/apt/lists/* \
           /tmp/* \
           /var/tmp/* && \
    apt-get clean
