"""Container tests for interactive completion and command manual pages."""

from __future__ import annotations

import subprocess

import pytest


DAR_MANUALS = (
    "dar",
    "dar_cp",
    "dar_manager",
    "dar_slave",
    "dar_split",
    "dar_xform",
)
PAR2_COMMANDS = (
    "par2",
    "par2create",
    "par2repair",
    "par2verify",
)


def _run_bash(
    image: str,
    command: str,
    *,
    interactive: bool,
) -> subprocess.CompletedProcess[str]:
    """Run Bash inside an image with captured text output.

    Args:
        image: Docker image reference under test.
        command: Bash command text to execute.
        interactive: Whether Bash should load its interactive startup files.

    Returns:
        Completed Docker subprocess without an automatic status check.
    """
    bash_option = "-ic" if interactive else "-lc"
    return subprocess.run(
        [
            "docker",
            "run",
            "--rm",
            "--entrypoint",
            "/bin/bash",
            image,
            bash_option,
            command,
        ],
        capture_output=True,
        text=True,
        check=False,
    )


def _complete_doc_prefix(image: str, prefix: str) -> subprocess.CompletedProcess[str]:
    """Request dar-backup documentation completions from a fresh shell.

    Args:
        image: Docker image reference under test.
        prefix: Partial documentation name to complete.

    Returns:
        Completed Docker subprocess containing one candidate per output line.
    """
    command = f"""
_completion_loader dar-backup >/dev/null 2>&1 || true
COMP_WORDS=(dar-backup --doc {prefix!r})
COMP_CWORD=2
COMP_LINE={f'dar-backup --doc {prefix}'!r}
COMP_POINT=${{#COMP_LINE}}
_python_argcomplete dar-backup {prefix!r} --doc
printf '%s\n' "${{COMPREPLY[@]}}"
"""
    return _run_bash(image, command, interactive=True)


def test_container_doc_completion_lists_packaged_topics(image: str) -> None:
    """A fresh interactive shell completes packaged documentation names.

    Args:
        image: Docker image fixture.
    """
    result = _complete_doc_prefix(image, "restoring")

    assert result.returncode == 0, result.stderr
    assert set(result.stdout.splitlines()) >= {
        "restoring",
        "restoring-advanced",
        "restoring-pitr",
    }


def test_container_doc_completion_unknown_prefix_returns_no_topic(image: str) -> None:
    """An unknown documentation prefix produces no fabricated completion.

    Args:
        image: Docker image fixture.
    """
    result = _complete_doc_prefix(image, "definitely-not-a-doc")

    assert result.returncode == 0, result.stderr
    assert not result.stdout.strip()


@pytest.mark.parametrize("manual_name", DAR_MANUALS)
def test_container_dar_manual_renders(image: str, manual_name: str) -> None:
    """Every manual generated by DAR renders through the real man system.

    Args:
        image: Docker image fixture.
        manual_name: DAR manual basename to render.
    """
    result = _run_bash(
        image,
        f"MANPAGER=cat PAGER=cat man {manual_name}",
        interactive=False,
    )

    assert result.returncode == 0, result.stderr
    assert manual_name.upper() in result.stdout


@pytest.mark.parametrize("command_name", PAR2_COMMANDS)
def test_container_par2_command_and_manual_are_available(
    image: str,
    command_name: str,
) -> None:
    """Every PAR2 command alias runs and has a renderable manual.

    Args:
        image: Docker image fixture.
        command_name: PAR2 command alias and manual basename to verify.
    """
    command_result = _run_bash(
        image,
        f"{command_name} --help",
        interactive=False,
    )
    manual_result = _run_bash(
        image,
        f"MANPAGER=cat PAGER=cat man {command_name}",
        interactive=False,
    )

    assert command_result.returncode == 0, command_result.stderr
    assert "Usage:" in command_result.stdout
    assert manual_result.returncode == 0, manual_result.stderr
    assert "PAR2" in manual_result.stdout


@pytest.mark.parametrize("command_name", PAR2_COMMANDS)
def test_container_par2_command_rejects_unknown_option(
    image: str,
    command_name: str,
) -> None:
    """Every PAR2 command alias reports an invalid option as an error.

    Args:
        image: Docker image fixture.
        command_name: PAR2 command alias to invoke.
    """
    result = _run_bash(
        image,
        f"{command_name} --definitely-invalid",
        interactive=False,
    )

    assert result.returncode != 0


def test_container_unknown_manual_fails(image: str) -> None:
    """The man system rejects a nonexistent page instead of using its stub.

    Args:
        image: Docker image fixture.
    """
    result = _run_bash(
        image,
        "MANPAGER=cat PAGER=cat man definitely-not-a-manual",
        interactive=False,
    )

    assert result.returncode != 0
    assert "No manual entry" in result.stderr
