"""
test_run_backup_script.py
=========================
Tests focused on scripts/run-backup.sh covering:

  1. WORKDIR-based default layout
  2. Explicit per-directory overrides (DAR_BACKUP_DIR, DAR_BACKUP_D_DIR,
     DAR_BACKUP_DATA_DIR, DAR_BACKUP_RESTORE_DIR)
  3. Failure paths — exit code ≠ 0 and meaningful error messages

Run with:
    pytest tests/test_run_backup_script.py -v

Prerequisites:
    - scripts/run-backup.sh is executable and on the path relative to CWD
    - The Docker image referenced by IMAGE env var (default: dar-backup:dev) is present
    - pytest, and the utils module (sha256sum, compare_to_originals) are available
"""

import os
import re
import shutil
import subprocess
import uuid
from pathlib import Path

import pytest

from utils import sha256sum

SCRIPT = "scripts/run-backup.sh"

DEFAULT_BACKUP_DEFINITION = """\
-am
-R /data
-z5
-n
--slice 7G
--cache-directory-tagging
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run_script(env_overrides, *args, expect_fail=False):
    """
    Invoke SCRIPT with *args, merging env_overrides into the current environment.

    Returns the CompletedProcess so callers can inspect stdout/stderr.
    When expect_fail=True the assertion is that returncode != 0.
    """
    env = os.environ.copy()
    env.update(env_overrides)
    result = subprocess.run([SCRIPT, *args], env=env, capture_output=True)
    stdout = result.stdout.decode()
    stderr = result.stderr.decode()
    print(f"\n--- STDOUT [{' '.join([SCRIPT, *args])}] ---\n{stdout}")
    print(f"--- STDERR [{' '.join([SCRIPT, *args])}] ---\n{stderr}")
    if expect_fail:
        assert result.returncode != 0, (
            f"Expected non-zero exit but got 0.\nSTDOUT:\n{stdout}\nSTDERR:\n{stderr}"
        )
    else:
        assert result.returncode == 0, (
            f"Script exited {result.returncode}.\nSTDOUT:\n{stdout}\nSTDERR:\n{stderr}"
        )
    return result


def make_dataset(data_dir: Path):
    """Write a small but realistic set of files into data_dir."""
    uid = uuid.uuid4().hex[:6]
    (data_dir / f"hello-{uid}.txt").write_text("Hello World\n")
    (data_dir / f"readme-{uid}.md").write_text("# Test dataset\nGenerated by pytest.\n")
    subprocess.run(
        ["dd", "if=/dev/urandom", f"of={data_dir}/bin-{uid}.bin", "bs=512K", "count=1"],
        check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def dar_files(backup_dir: Path, definition: str, btype: str) -> list:
    """Return .dar files matching <definition>_<btype>_YYYY-MM-DD.<n>.dar."""
    pat = re.compile(
        rf"^{re.escape(definition)}_{btype}_\d{{4}}-\d{{2}}-\d{{2}}\.\d+\.dar$"
    )
    return [f for f in backup_dir.glob("*.dar") if pat.match(f.name)]


def build_base_env(workdir: Path) -> dict:
    """Minimal environment that run-backup.sh needs."""
    return {
        "WORKDIR": str(workdir),
        "RUN_AS_UID": str(os.getuid()),
        "RUN_AS_GID": str(os.getgid()),
    }


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def workdir_env(tmp_path):
    """
    Provides a self-contained WORKDIR layout using only the WORKDIR variable.
    The script is expected to derive all sub-directories from WORKDIR.
    """
    workdir = tmp_path / "workdir"
    for sub in ("backups", "backup.d", "data", "restore"):
        (workdir / sub).mkdir(parents=True)
    (workdir / "backup.d" / "default").write_text(DEFAULT_BACKUP_DEFINITION)
    make_dataset(workdir / "data")
    yield workdir


@pytest.fixture()
def explicit_dirs_env(tmp_path):
    """
    Provides an environment where every directory is set *explicitly*,
    none of them under a shared WORKDIR.
    """
    backups   = tmp_path / "my_backups"
    backup_d  = tmp_path / "my_definitions"
    data      = tmp_path / "my_data"
    restore   = tmp_path / "my_restore"
    for d in (backups, backup_d, data, restore):
        d.mkdir(parents=True)
    (backup_d / "default").write_text(DEFAULT_BACKUP_DEFINITION)
    make_dataset(data)
    yield {
        "backups":  backups,
        "backup_d": backup_d,
        "data":     data,
        "restore":  restore,
    }


# ===========================================================================
# Section 1 – WORKDIR-based default layout
# ===========================================================================

class TestWorkdirLayout:
    """Behaviour when only WORKDIR is set; all sub-dirs default from it."""

    def test_full_backup_creates_dar_files(self, workdir_env):
        """FULL backup via WORKDIR produces at least one .dar in workdir/backups."""
        env = build_base_env(workdir_env)
        run_script(env, "-t", "FULL")
        assert any((workdir_env / "backups").glob("*.dar")), \
            "Expected .dar files in workdir/backups after FULL backup"

    def test_full_diff_incr_chain(self, workdir_env):
        """
        WORKDIR layout supports a complete FULL → DIFF → INCR chain,
        each stage producing its own .dar file set.
        """
        env = build_base_env(workdir_env)
        data = workdir_env / "data"
        backups = workdir_env / "backups"

        run_script(env, "-t", "FULL")
        assert dar_files(backups, "default", "FULL"), "No FULL .dar files"

        (data / "delta.txt").write_text("change for DIFF\n")
        run_script(env, "-t", "DIFF")
        assert dar_files(backups, "default", "DIFF"), "No DIFF .dar files"

        (data / "delta2.txt").write_text("change for INCR\n")
        run_script(env, "-t", "INCR")
        assert dar_files(backups, "default", "INCR"), "No INCR .dar files"

    def test_script_prints_workdir_in_output(self, workdir_env):
        """The script should echo the base directory it is using."""
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "FULL")
        stdout = result.stdout.decode()
        assert str(workdir_env) in stdout, \
            "Expected WORKDIR path to appear in script output"

    def test_missing_type_flag_fails_with_usage_hint(self, workdir_env):
        """
        Omitting -t must exit non-zero and the output must contain a usage hint
        so the operator knows what went wrong.
        """
        env = build_base_env(workdir_env)
        result = run_script(env, expect_fail=True)
        combined = result.stdout.decode() + result.stderr.decode()
        assert "FULL" in combined or "usage" in combined.lower() or "Usage" in combined, \
            "Error output should contain a usage/help hint mentioning FULL|DIFF|INCR"

    def test_workdir_subdirectories_are_auto_created(self, tmp_path):
        """
        When WORKDIR points at a directory without sub-dirs, the script must
        create backups/, backup.d/, data/, restore/ automatically.
        """
        workdir = tmp_path / "auto_create"
        workdir.mkdir()
        # Write definition and data manually because script won't have data to back up otherwise
        (workdir / "backup.d").mkdir()
        (workdir / "backup.d" / "default").write_text(DEFAULT_BACKUP_DEFINITION)
        (workdir / "data").mkdir()
        make_dataset(workdir / "data")
        env = build_base_env(workdir)
        run_script(env, "-t", "FULL")
        for sub in ("backups", "backup.d", "data", "restore"):
            assert (workdir / sub).is_dir(), f"Expected {sub}/ to exist after run"

    def test_default_definition_file_is_created_if_absent(self, tmp_path):
        """
        If backup.d/default does not exist the script must create it and still
        succeed.
        """
        workdir = tmp_path / "nodef"
        for sub in ("backups", "backup.d", "data", "restore"):
            (workdir / sub).mkdir(parents=True)
        make_dataset(workdir / "data")
        env = build_base_env(workdir)
        # No default definition written intentionally
        run_script(env, "-t", "FULL")
        assert (workdir / "backup.d" / "default").exists(), \
            "Script should auto-create backup.d/default"

    def test_case_insensitive_backup_type(self, tmp_path):
        """
        Backup type flags should be accepted in any case (full, Full, FULL).

        Each variant gets its own isolated workdir because dar-backup enforces
        a "one FULL per day" rule: re-running the same type in the same backup
        directory on the same day exits non-zero.  Using separate directories
        keeps the runs independent and the test honest.
        """
        for variant in ("full", "Full", "FULL"):
            workdir = tmp_path / f"case_{variant}"
            for sub in ("backups", "backup.d", "data", "restore"):
                (workdir / sub).mkdir(parents=True)
            (workdir / "backup.d" / "default").write_text(DEFAULT_BACKUP_DEFINITION)
            make_dataset(workdir / "data")
            env = build_base_env(workdir)
            run_script(env, "-t", variant)

    def test_incremental_longform_alias(self, workdir_env):
        """--type incremental is accepted as an alias for INCR."""
        env = build_base_env(workdir_env)
        data = workdir_env / "data"
        backups = workdir_env / "backups"

        run_script(env, "-t", "FULL")
        (data / "extra.txt").write_text("for incr\n")
        run_script(env, "-t", "DIFF")
        (data / "extra2.txt").write_text("for incr 2\n")
        run_script(env, "-t", "incremental")   # long alias
        assert dar_files(backups, "default", "INCR"), \
            "No INCR .dar files when using 'incremental' alias"


# ===========================================================================
# Section 2 – Explicit per-directory overrides
# ===========================================================================

class TestExplicitDirectoryOverrides:
    """Every directory can be set independently, overriding WORKDIR defaults."""

    def _env(self, dirs: dict) -> dict:
        """Build the env dict from the dirs fixture."""
        return {
            "DAR_BACKUP_DIR":         str(dirs["backups"]),
            "DAR_BACKUP_D_DIR":       str(dirs["backup_d"]),
            "DAR_BACKUP_DATA_DIR":    str(dirs["data"]),
            "DAR_BACKUP_RESTORE_DIR": str(dirs["restore"]),
            "RUN_AS_UID":             str(os.getuid()),
            "RUN_AS_GID":             str(os.getgid()),
            # Provide a WORKDIR that is *different* from the explicit dirs
            # so we can confirm the overrides win.
            "WORKDIR": "/tmp/should-not-be-used",
        }

    def test_full_backup_honours_dar_backup_dir(self, explicit_dirs_env):
        """DAR archives land in DAR_BACKUP_DIR, not the default WORKDIR/backups."""
        env = self._env(explicit_dirs_env)
        run_script(env, "-t", "FULL")
        assert any(explicit_dirs_env["backups"].glob("*.dar")), \
            "Expected .dar files in the explicit DAR_BACKUP_DIR"
        # The would-be default path must NOT have been used
        assert not Path("/tmp/should-not-be-used/backups").exists() or \
               not any(Path("/tmp/should-not-be-used/backups").glob("*.dar")), \
               "Archives appeared in WORKDIR/backups instead of DAR_BACKUP_DIR"

    def test_full_diff_incr_chain_with_explicit_dirs(self, explicit_dirs_env):
        """Complete chain works when all four dirs are explicitly set."""
        env = self._env(explicit_dirs_env)
        data = explicit_dirs_env["data"]
        backups = explicit_dirs_env["backups"]

        run_script(env, "-t", "FULL")
        assert dar_files(backups, "default", "FULL")

        (data / "new_for_diff.txt").write_text("diff data\n")
        run_script(env, "-t", "DIFF")
        assert dar_files(backups, "default", "DIFF")

        (data / "new_for_incr.txt").write_text("incr data\n")
        run_script(env, "-t", "INCR")
        assert dar_files(backups, "default", "INCR")

    def test_custom_backup_definition_via_override(self, explicit_dirs_env):
        """A named definition in DAR_BACKUP_D_DIR is found and used."""
        env = self._env(explicit_dirs_env)
        def_name = "myproject"
        (explicit_dirs_env["backup_d"] / def_name).write_text(
            "-am\n-R /data\n-z1\n--slice 1G\n"
        )
        run_script(env, "-t", "FULL", "-d", def_name)
        assert dar_files(explicit_dirs_env["backups"], def_name, "FULL"), \
            f"No FULL .dar files for definition '{def_name}'"

    def test_only_dar_backup_dir_overridden(self, workdir_env):
        """
        Overriding just DAR_BACKUP_DIR redirects archive output while the other
        three dirs remain under WORKDIR.
        """
        custom_backups = workdir_env.parent / "custom_backups_only"
        custom_backups.mkdir(parents=True, exist_ok=True)
        env = build_base_env(workdir_env)
        env["DAR_BACKUP_DIR"] = str(custom_backups)
        run_script(env, "-t", "FULL")
        assert any(custom_backups.glob("*.dar")), \
            "Expected archives in the overridden DAR_BACKUP_DIR"
        assert not any((workdir_env / "backups").glob("*.dar")), \
            "Archives must not appear in the default WORKDIR/backups"

    def test_only_data_dir_overridden(self, workdir_env, tmp_path):
        """
        Overriding DAR_BACKUP_DATA_DIR sources from that path, not WORKDIR/data.
        """
        custom_data = tmp_path / "special_data"
        custom_data.mkdir()
        make_dataset(custom_data)
        env = build_base_env(workdir_env)
        env["DAR_BACKUP_DATA_DIR"] = str(custom_data)
        run_script(env, "-t", "FULL")
        assert any((workdir_env / "backups").glob("*.dar")), \
            "Expected archives even when using a custom data dir"

    def test_script_echoes_explicit_dir_values(self, explicit_dirs_env):
        """Each overridden path should appear somewhere in the script's output."""
        env = self._env(explicit_dirs_env)
        result = run_script(env, "-t", "FULL")
        stdout = result.stdout.decode()
        for key, path in explicit_dirs_env.items():
            assert str(path) in stdout, \
                f"Expected '{path}' ({key}) to appear in script output"


# ===========================================================================
# Section 3 – Failure paths and error messages
# ===========================================================================

class TestFailurePaths:
    """
    Each test verifies that the script exits non-zero AND that the error
    output contains a meaningful message — not a cryptic shell trace.
    """

    def _combined(self, result) -> str:
        return result.stdout.decode() + result.stderr.decode()

    # --- Argument / option errors ---

    def test_missing_t_flag(self, workdir_env):
        """No -t flag → non-zero exit with usage line."""
        env = build_base_env(workdir_env)
        result = run_script(env, expect_fail=True)
        msg = self._combined(result)
        assert "FULL" in msg or "-t" in msg, \
            "Should mention -t / FULL|DIFF|INCR in error output"

    def test_t_flag_without_value(self, workdir_env):
        """-t with no following value must exit non-zero with a clear complaint."""
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", expect_fail=True)
        msg = self._combined(result)
        # Bash will surface either an argument error or usage
        assert result.returncode != 0

    def test_invalid_backup_type(self, workdir_env):
        """An unrecognised -t value must exit non-zero and name the bad value."""
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "WEEKLY", expect_fail=True)
        msg = self._combined(result)
        assert "WEEKLY" in msg or "Invalid" in msg or "invalid" in msg, \
            "Error output should identify the invalid type"

    def test_unknown_option(self, workdir_env):
        """An unknown flag like --frobnicate must exit non-zero."""
        env = build_base_env(workdir_env)
        result = run_script(env, "--frobnicate", expect_fail=True)
        msg = self._combined(result)
        assert "frobnicate" in msg or "Unknown" in msg or "unknown" in msg, \
            "Error output should identify the unknown option"

    def test_d_flag_without_value(self, workdir_env):
        """-d with no value must exit non-zero with a helpful message."""
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "FULL", "-d", expect_fail=True)
        assert result.returncode != 0

    def test_nonexistent_definition_file(self, workdir_env):
        """Specifying a definition that does not exist must fail clearly."""
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "FULL", "-d", "ghost-definition", expect_fail=True)
        # Just non-zero exit is the minimum guarantee from the script;
        # dar-backup itself will surface the missing file error.
        assert result.returncode != 0

    # --- UID/root guard ---

    def test_root_uid_is_rejected(self, workdir_env):
        """RUN_AS_UID=0 must exit non-zero with a message about root not being allowed."""
        env = build_base_env(workdir_env)
        env["RUN_AS_UID"] = "0"
        result = run_script(env, "-t", "FULL", expect_fail=True)
        msg = self._combined(result)
        assert "root" in msg.lower(), \
            "Error message should mention 'root' when UID 0 is rejected"

    # --- Docker image errors ---

    def test_nonexistent_docker_image_fails(self, workdir_env):
        """Pointing IMAGE at a non-existent tag must fail (docker can't find it)."""
        env = build_base_env(workdir_env)
        env["IMAGE"] = "dar-backup:this-tag-does-not-exist-at-all"
        env["DOCKER_PULL"] = "false"
        result = run_script(env, "-t", "FULL", expect_fail=True)
        assert result.returncode != 0

    # --- Directory / path guard ---

    def test_root_slash_as_backup_dir_is_rejected(self, workdir_env):
        """DAR_BACKUP_DIR=/ must be refused before any Docker call."""
        env = build_base_env(workdir_env)
        env["DAR_BACKUP_DIR"] = "/"
        result = run_script(env, "-t", "FULL", expect_fail=True)
        msg = self._combined(result)
        assert "/" in msg and ("Refusing" in msg or "refusing" in msg or result.returncode != 0), \
            "Script should refuse to use / as backup dir"

    def test_root_slash_as_data_dir_is_rejected(self, workdir_env):
        """DAR_BACKUP_DATA_DIR=/ must be refused before any Docker call."""
        env = build_base_env(workdir_env)
        env["DAR_BACKUP_DATA_DIR"] = "/"
        result = run_script(env, "-t", "FULL", expect_fail=True)
        assert result.returncode != 0

    # --- Positional argument noise ---

    def test_unexpected_positional_argument(self, workdir_env):
        """Stray positional arguments after valid flags must cause a non-zero exit."""
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "FULL", "unexpected_extra", expect_fail=True)
        msg = self._combined(result)
        assert "unexpected" in msg.lower() or result.returncode != 0, \
            "Script should reject unexpected positional arguments"

    # --- Exit code is exactly non-zero (not just non-zero) ---

    def test_exit_code_is_1_for_missing_t(self, workdir_env):
        """
        The script should exit with code 1 (not e.g. 127 or 2) for a usage
        error so callers can distinguish it from 'command not found'.
        """
        env = build_base_env(workdir_env)
        env_full = os.environ.copy()
        env_full.update(env)
        result = subprocess.run([SCRIPT], env=env_full, capture_output=True)
        assert result.returncode == 1, \
            f"Expected exit code 1 for missing -t, got {result.returncode}"

    def test_exit_code_is_1_for_root_uid(self, workdir_env):
        """Root UID rejection should also exit with code 1."""
        env = build_base_env(workdir_env)
        env["RUN_AS_UID"] = "0"
        env_full = os.environ.copy()
        env_full.update(env)
        result = subprocess.run([SCRIPT, "-t", "FULL"], env=env_full, capture_output=True)
        assert result.returncode == 1, \
            f"Expected exit code 1 for root UID, got {result.returncode}"

    # --- WORKDIR guard ---

    def test_fail_when_workdir_not_set(self):
        """
        An unset WORKDIR must exit non-zero with a message that mentions WORKDIR,
        so the operator immediately knows what to fix.
        """
        env = os.environ.copy()
        env.pop("WORKDIR", None)
        env["RUN_AS_UID"] = str(os.getuid())
        env["RUN_AS_GID"] = str(os.getgid())
        result = subprocess.run([SCRIPT, "-t", "FULL"], env=env, capture_output=True)
        assert result.returncode != 0, \
            "Script must exit non-zero when WORKDIR is not set"
        msg = result.stdout.decode() + result.stderr.decode()
        assert "WORKDIR" in msg, \
            "Error output must mention 'WORKDIR' so the operator knows what to fix"

    def test_exit_code_is_1_for_missing_workdir(self):
        """WORKDIR not set should exit with code 1, consistent with other guard exits."""
        env = os.environ.copy()
        env.pop("WORKDIR", None)
        env["RUN_AS_UID"] = str(os.getuid())
        env["RUN_AS_GID"] = str(os.getgid())
        result = subprocess.run([SCRIPT, "-t", "FULL"], env=env, capture_output=True)
        assert result.returncode == 1, \
            f"Expected exit code 1 for missing WORKDIR, got {result.returncode}"


# ===========================================================================
# Section 4 – Image identification output
# ===========================================================================

class TestImageIdentificationOutput:
    """
    The script prints either 'Image Digest:' (for pulled images with a registry
    digest) or 'Image Id:' (for locally built images without a RepoDigest).
    Exactly one of the two labels must appear — never both, never neither.
    """

    def test_output_contains_image_digest_or_image_id(self, workdir_env):
        """
        After a successful run the output must contain either
        'Image Digest:' or 'Image Id:' but not both.
        """
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "FULL")
        stdout = result.stdout.decode()
        has_digest = "Image Digest:" in stdout
        has_id     = "Image Id:"     in stdout
        assert has_digest or has_id, \
            "Output must contain either 'Image Digest:' or 'Image Id:'"
        assert not (has_digest and has_id), \
            "Output must not contain both 'Image Digest:' and 'Image Id:' at the same time"

    def test_image_digest_line_contains_sha256(self, workdir_env):
        """
        When 'Image Digest:' is printed the value on that line must look like
        a sha256 hash (64 hex chars), as returned by a registry pull.
        Skipped automatically when the image has no RepoDigest (locally built).
        """
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "FULL")
        stdout = result.stdout.decode()
        if "Image Digest:" not in stdout:
            pytest.skip("Image has no RepoDigest (locally built); skipping digest format check")
        line = next(l for l in stdout.splitlines() if "Image Digest:" in l)
        assert re.search(r"sha256:[0-9a-f]{64}", line), \
            f"'Image Digest:' line does not contain a valid sha256 hash: {line!r}"

    def test_image_id_line_contains_sha256(self, workdir_env):
        """
        When 'Image Id:' is printed the value on that line must look like
        a sha256 hash (64 hex chars), as produced by a local build.
        Skipped automatically when the image was pulled and has a RepoDigest.
        """
        env = build_base_env(workdir_env)
        result = run_script(env, "-t", "FULL")
        stdout = result.stdout.decode()
        if "Image Id:" not in stdout:
            pytest.skip("Image has a RepoDigest (pulled from registry); skipping Id format check")
        line = next(l for l in stdout.splitlines() if "Image Id:" in l)
        assert re.search(r"sha256:[0-9a-f]{64}", line), \
            f"'Image Id:' line does not contain a valid sha256 hash: {line!r}"
