#!/usr/bin/env python3
"""
scripts/update_pages.py

Regenerates docs/index.html from docs/index.template.html by injecting
the last N releases from doc/build-history.json between the
@@RELEASES_START@@ / @@RELEASES_END@@ markers.

Usage (from repo root):
    python3 scripts/update_pages.py                  # releases only (default)
    python3 scripts/update_pages.py --include-refreshes  # include weekly -N builds

Called automatically from the release workflow (step 12) after
update_build_log.py has already appended the new entry.
Also called from image-refresh.yml after each weekly refresh.
"""

import argparse
import json
import re
import sys
from pathlib import Path

# ── paths (relative to repo root) ────────────────────────────────────────────
HISTORY_FILE  = Path("doc/build-history.json")
TEMPLATE_FILE = Path("docs/index.template.html")
OUTPUT_FILE   = Path("docs/index.html")
NUM_RELEASES  = 5

# ── injection markers ─────────────────────────────────────────────────────────
START_MARKER = "<!-- @@RELEASES_START@@ -->"
END_MARKER   = "<!-- @@RELEASES_END@@ -->"

# Matches versioned releases: 0.5.24
# Does NOT match weekly refreshes: 0.5.22-1
RELEASE_RE = re.compile(r"^\d+\.\d+\.\d+$")
# Matches both releases and refreshes
ANY_VERSION_RE = re.compile(r"^\d+\.\d+\.\d+(-\d+)?$")


def load_history(include_refreshes: bool) -> list[dict]:
    with HISTORY_FILE.open() as f:
        data = json.load(f)
    pattern = ANY_VERSION_RE if include_refreshes else RELEASE_RE
    valid = [e for e in data if pattern.match(e.get("tag", ""))]
    return sorted(valid, key=lambda e: e.get("build_number", 0), reverse=True)


def grype_badge(entry: dict) -> str:
    grype  = entry.get("grype_scan", {})
    counts = grype.get("counts", {})
    if not grype:
        return ""
    critical = counts.get("critical", 0)
    high     = counts.get("high", 0)
    if critical == 0 and high == 0:
        return '<span class="release-grype grype-clean">0 H/C</span>'
    return (f'<span class="release-grype grype-warn">'
            f'{high}H&nbsp;{critical}C</span>')


def rekor_link(entry: dict) -> str:
    url = entry.get("cosign", {}).get("rekor_log_entry", "")
    if not url:
        return ""
    return f'<a href="{url}" class="release-link rekor" target="_blank">Rekor&nbsp;→</a>'


def dockerhub_link(entry: dict) -> str:
    url = entry.get("dockerhub_tag_url", "")
    if not url:
        return ""
    return f'<a href="{url}" class="release-link" target="_blank">Docker&nbsp;Hub&nbsp;→</a>'


def render_row(entry: dict, is_latest: bool) -> str:
    tag           = entry.get("tag", "?")
    dar_bkp_ver   = entry.get("dar_backup_version", "—")
    created       = entry.get("created", "")[:10]
    git_rev       = entry.get("git_revision", "—")
    latest_badge  = '<span class="latest">&#9679;&nbsp;Latest</span>' if is_latest else ""

    return (
        f'    <div class="release-row">\n'
        f'      <div class="release-tag">{tag}</div>\n'
        f'      <div class="release-meta">\n'
        f'        <span>dar-backup&nbsp;{dar_bkp_ver}</span>\n'
        f'        <span>{created}</span>\n'
        f'        <span class="git-rev">{git_rev}</span>\n'
        f'        {latest_badge}\n'
        f'      </div>\n'
        f'      <div class="release-actions">\n'
        f'        {grype_badge(entry)}\n'
        f'        {dockerhub_link(entry)}\n'
        f'        {rekor_link(entry)}\n'
        f'      </div>\n'
        f'    </div>'
    )


def build_block(entries: list[dict]) -> str:
    rows = "\n".join(
        render_row(e, is_latest=(i == 0))
        for i, e in enumerate(entries[:NUM_RELEASES])
    )
    return (
        f"{START_MARKER}\n"
        f"  <!-- auto-generated by scripts/update_pages.py — do not edit manually -->\n"
        f"  <div class=\"releases reveal\">\n"
        f"{rows}\n"
        f"  </div>\n"
        f"  {END_MARKER}"
    )


def inject(template: str, block: str) -> str:
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    result, n = pattern.subn(block, template)
    if n == 0:
        sys.exit(
            f"ERROR: injection markers not found in template.\n"
            f"Expected '{START_MARKER}' ... '{END_MARKER}'"
        )
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--include-refreshes", action="store_true",
        help="Include weekly refresh builds (e.g. 0.5.22-1) in the table"
    )
    args = parser.parse_args()

    for path in (HISTORY_FILE, TEMPLATE_FILE):
        if not path.exists():
            sys.exit(f"ERROR: {path} not found (run from repo root)")

    entries = load_history(args.include_refreshes)
    if not entries:
        sys.exit("ERROR: no valid release entries found in build-history.json")

    template = TEMPLATE_FILE.read_text()
    block    = build_block(entries)
    output   = inject(template, block)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output)

    latest = entries[0].get("tag")
    shown  = min(len(entries), NUM_RELEASES)
    mode   = "releases+refreshes" if args.include_refreshes else "releases"
    print(f"✅  docs/index.html updated — {shown} {mode} shown, latest: {latest}")


if __name__ == "__main__":
    main()
