name: CI - Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
permissions:
  contents: read

jobs:
  build-and-test:
    name: Build dev image and run tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install required system packages
        run: |
          sudo apt update
          sudo apt install -y python3 pytest 

      - name: Build base ubuntu 24.04 image, and then the dev image
        run: |
          make FINAL_VERSION=dev DAR_BACKUP_VERSION=0.8.2 dev

      - name: Run FULL, DIFF & INCR tests
        run: make test

      - name: Run integration tests
        run: make FINAL_VERSION=dev DAR_BACKUP_VERSION=0.8.2 test-integration
