name: CI - Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
permissions:
  contents: read

jobs:
  build-and-test:
    name: Build dev image and run tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        run: make dev

      - name: Run integration tests
        run: make test
